# For more information: https://laravel.com/docs/sail
version: '3'
services:
    frontend:
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - "8888:80"
        volumes:
            - ./:/var/www
            - ./nginx/site.conf/:/etc/nginx/conf.d/
        networks:
            - app-network
    backend:
        build:
            context: ./
            dockerfile: ./docker/Dockerfile
        image: app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        volumes:
            - '.:/var/www/html'
        networks:
            - app-network

networks:
  app-network:
    driver: bridge